config/routes.rb
KppControlSystem::Application.routes.draw do

  devise_for :users, :controller => { :sessions => 'users/sessions' }

  devise_for :admins
  
  resources :offices do
    resources :employees
    resources :users
  end

  resources :employees do
    resources :visits
  end

  resources :visits

  resources :users

  root :to => "home#index"

end

app/models/office.rb
class Office < ActiveRecord::Base
  attr_accessible :address, :name

  validates :name,	:presence => true
  validates :address,	:presence => true,
			:length => { :minimum => 5 }

  has_many :employees
  has_many :users
  has_many :visits
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController

  # before_filter :authenticate, :except => [:index]
  
  before_filter :authenticate_admin!

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @offices }
    end
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
    @office = Office.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @office }
    end
  end

  # GET /offices/new
  # GET /offices/new.json
  def new
    @office = Office.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @office }
    end
  end

  # GET /offices/1/edit
  def edit
    @office = Office.find(params[:id])
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(params[:office])

    respond_to do |format|
      if @office.save
        format.html { redirect_to new_office_user_path(@office), notice: 'Office was successfully created. Now create an account for office KPP manager.' }
        format.json { render json: @office, status: :created, location: @office }
      else
        format.html { render action: "new" }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /offices/1
  # PUT /offices/1.json
  def update
    @office = Office.find(params[:id])

    respond_to do |format|
      if @office.update_attributes(params[:office])
        format.html { redirect_to offices_path, notice: 'Office was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office = Office.find(params[:id])
    @office.destroy

    respond_to do |format|
      format.html { redirect_to offices_url }
      format.json { head :no_content }
    end
  end

  private
    def authenticate
      authenticate_or_request_with_http_digest(REALM) do |username|
        USERS[username]
      end
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<%= form_for(@office) do |f| %>
  <% if @office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% @office.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %> <%= link_to 'Отмена', offices_path, :class => 'btn' %>
  </div>
<% end %>

app/views/offices/edit.html.erb
<h1>Editing office</h1>

<%= render 'form' %>

app/views/offices/index.html.erb
<h1>Отделения</h1>

<table>
<% @offices.each do |office| %>
  <tr>
    <td><%= link_to office.name, office %></td>
    <td><%= office.address %></td>
    <td><%= link_to 'Изменить', edit_office_path(office) %></td>
    <td><%= link_to 'Удалить', office, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Добавить', new_office_path, :class => 'btn' %>

app/views/offices/new.html.erb
<h1>Добавление отделения</h1>

<%= render 'form' %>

app/views/offices/show.html.erb
<h1>
  <%= @office.name %>
</h1>

<div style="text-align: center; padding-bottom: 25px;">
    <%= @office.address %>
  &nbsp; &nbsp;
    <% if @office.users.empty? %>
      Работник КПП: <%= link_to 'Создать аккаунт', new_office_user_path(@office) %>
    <% else %>
      Работник КПП: <%= link_to @office.users.first.email, edit_user_path(@office.users.first) %>
    <% end %>
</div>

<h2>Сотрудники отделения</h2>

<table>
  <%= render @office.employees %>
</table>

<br />

<%= link_to 'Добавить сотрудника', new_office_employee_path(@office), :class => 'btn' %>