config/routes.rb
KppControlSystem::Application.routes.draw do

  devise_for :users, :controller => { :sessions => 'users/sessions' }

  devise_for :admins
  
  resources :offices do
    resources :employees
    resources :users
  end

  resources :employees do
    resources :visits
  end

  resources :visits

  resources :users

  root :to => "home#index"

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :office
  has_many :visits, :dependent => :destroy
  attr_accessible :name, :post

  validates :name,	:presence => true,
			:length => { :minimum => 10 }
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  
  before_filter :authenticate_admin!
  
  # GET /employees
  # GET /employees.json
  def index
  if params[:office_id].nil?
    @employees = Employee.all
  else
    @office = Office.find(params[:office_id])
    @employees = @office.employees
  end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
  if params[:office_id].nil?
    @employee = Employee.new
    @back = employees_path
  else
    @office = Office.find(params[:office_id])
    @employee = @office.employees.new
    @back = @office
  end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
    if params[:office_id].nil?
      @back = employees_path
    else
      @back = Office.find(params[:office_id])
    end
  end

  # POST /employees
  # POST /employees.json
  def create
  if params[:office_id].nil?
    @employee = Employee.new(params[:employee])
  else
    @office = Office.find(params[:office_id])
    @employee = @office.employees.new(params[:employee])
  end

    respond_to do |format|
      if @employee.save
        format.html { if @office.nil?
                        redirect_to employees_path, notice: 'Employee was successfully created.'
                      else
                        redirect_to @office, notice: 'Employee was successfully created.'
                      end }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { if @office.nil?
                        redirect_to employees_path, notice: 'Employee was successfully updated.'
                      else
                        redirect_to office_employees_path(@office), notice: 'Employee was successfully updated.'
                      end }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    if @employee.office.nil?
      @back = employees_path
    else
      @back = @employee.office
    end
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to @back }
      format.json { head :no_content }
    end
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_employee.html.erb
  <tr>
    <td><%= link_to employee.name, employee_visits_path(employee) %></td>
    <td><%= employee.post %></td>
    <td><%= link_to 'Изменить', edit_office_employee_path(employee.office, employee) %></td>
    <td><%= link_to 'Удалить', [employee.office, employee], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>

app/views/employees/_form.html.erb
<% if @employee.office.nil?
     @form_path = @employee
   else
     @form_path = [@employee.office, @employee]
   end %>

<%= form_for(@form_path) do |f| %>
  <% if @employee.errors.any? %>
    <div class="alert alert-error">
      <a class="close" data-dismiss="alert">&#215;</a>
      <h3><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h3>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label 'Имя' %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label 'Должность' %>
    <%= f.text_field :post %>
  </div>
  <div class="actions">
    <%= f.submit :class => 'btn btn-primary' %> <%= link_to 'Отмена', @back, :class => 'btn' %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Изменение сотрудника</h1>

<%= render 'form' %>

app/views/employees/index.html.erb
<h1>Сотрудники</h1>

<table>
<% @employees.each do |employee| %>
  <tr>
    <td><%= link_to employee.name, employee_visits_path(employee) %><br /><span style="font-size: 12px;"><%= employee.post %></span></td>
    <td><%= if !employee.office.nil?; link_to employee.office.name, employee.office; end %></td>
    <td><%= link_to 'Изменить', edit_employee_path(employee) %></td>
    <td><%= link_to 'Удалить', employee_url(employee), :method => :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

app/views/employees/new.html.erb
<h1>Добавление сотрудника</h1>

<%= render 'form' %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Post:</b>
  <%= @employee.post %>
</p>

<p>
  <b>Office:</b>
  <%= @employee.office %>
</p>


<%= link_to 'Edit', edit_office_employee_path(@employee) %> |
<%= link_to 'Back', office_employees_path %>