config/routes.rb
KppControlSystem::Application.routes.draw do

  devise_for :users, :controller => { :sessions => 'users/sessions' }

  devise_for :admins
  
  resources :offices do
    resources :employees
    resources :users
  end

  resources :employees do
    resources :visits
  end

  resources :visits

  resources :users

  root :to => "home#index"

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  attr_accessible :inout, :employee
  belongs_to :office
  belongs_to :employee
  default_scope :order => "id DESC"
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  
  before_filter :authenticate_user!
  
  # GET /visits
  # GET /visits.json
  def index
    if params[:employee_id].nil?
      if admin_signed_in?
        @visits = Visit.all
      else
        @visits = Visit.where( :office_id => current_user.office.id )
      end
    else
      @visits = Visit.where( :employee_id => params[:employee_id])
    end

    @visit = Visit.new

    @employees_names = []
    Employee.all.each { |e| @employees_names.push(e.name) }

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @visits }
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    @visit = Visit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new
    @visit = Visit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @visit }
    end
  end

  # GET /visits/1/edit
  def edit
    @visit = Visit.find(params[:id])
  end

  # POST /visits
  # POST /visits.json
  def create
    @e = Employee.find_by_name(params[:visit][:employee]) ? Employee.find_by_name(params[:visit][:employee]) : Employee.create( :name => params[:visit][:employee] )
    @visit = current_user.office.visits.new( :employee => @e, :inout => params[:visit][:inout] )

    respond_to do |format|
      if @visit.save
        format.html { redirect_to visits_path, notice: 'Visit was successfully created.' }
        format.json { render json: @visit, status: :created, location: @visit }
      else
        format.html { render action: "new" }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @id = params[:id]
    @visit = Visit.find(@id)
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
      format.js
    end
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for @visit, :remote => true, :update => '#feedback', :class => 'form-inline' do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul style="text-align: left; font-size: 14px;">
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="well" style="padding: 10px;">Кто тут?
    <!-- %= f.text_field :employee, :class => 'big-input typeahead' % -->
    <input class="big-input typeahead" id="visit_employee" name="visit[employee]" size="30" type="text" data-provide="typeahead" data-items="<%= @employees_names.count.to_s %>" data-source="<%= @employees_names.to_json %>">
    <button class="btn" name="visit[inout]" value="in"><i class='icon-arrow-right'></i> Пришел</button> или 
    <button class="btn" name="visit[inout]" value="out"><i class='icon-arrow-left'></i> Уходит</button>
  </div>

<% end %>

<div id="feedback"></div>

app/views/visits/_visit.html.erb
  <tr id="<%= visit.id %>">
    <td><%= visit.created_at.to_s(:time) %> <span class="date"><%= visit.created_at.to_s(:date) %></span></td>
    <td><%= if !visit.employee.nil?; link_to visit.employee.name, employee_visits_path(visit.employee); end %></td>
    <td><% if visit.inout == 'in' %>
    <i class="icon-arrow-right"></i>
    <% end %>
    <% if visit.inout == 'out' %>
    <i class="icon-arrow-left"></i>
    <% end %></td>
    <td><%= if !visit.office.nil?; visit.office.name; end %></td>
    <td><%= link_to 'Удалить', visit_url(visit), :method => 'delete', :remote => true %></td>
  </tr>

app/views/visits/create.js.erb
<% if @visit.errors.any? %>
  <% flash[:error] = 'Что-то ужасное призошло =(' %>
  $('div.span12:first').prepend('<%= render 'layouts/messages' %>');
<% else %>
  $('table#visits').prepend('<%= escape_javascript( render @visit ) %>');
  $('.big-input').val('');
  $('.big-input').focus();
<% end %>

app/views/visits/destroy.js.erb
$('tr#<%= @id %>').fadeOut()

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Журнал посетителей</h1>

<%= render 'form' %>

<h2 style="text-align: center; padding-bottom: 20px;">Еще ходили</h2>

<table id="visits">
  <%= render @visits %>
</table>

<br />

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

app/views/visits/show.html.erb
<table>
<%= render @visit %>
</table>