config/routes.rb
KppControlSystem::Application.routes.draw do

  devise_for :users, :controller => { :sessions => 'users/sessions' }

  devise_for :admins
  
  resources :offices do
    resources :employees
    resources :users
  end

  resources :employees do
    resources :visits
  end

  resources :visits

  resources :users

  root :to => "home#index"

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
          <ul class="nav">
		<li<% if current_page?(root_path); %> class="active"<% end; %>>
			<%= link_to 'КПП', root_path, :class => 'brand' %>
		</li>
                <% if admin_signed_in? %>
		<li<% if current_page?(offices_path); %> class="active"<% end; %>>
		  <%= link_to "Отделения", offices_path %>
		</li>
		<li<% if current_page?(employees_path); %> class="active"<% end; %>>
		  <%= link_to "Сотрудники", employees_path %>
		</li>
		<li<% if current_page?(users_path); %> class="active"<% end; %>>
		  <%= link_to "Аккаунты", users_path %>
		</li>
		<li<% if current_page?(visits_path); %> class="active"<% end; %>>
		  <%= link_to "Журнал посетителей", visits_path %>
		</li>
                <% else %>
                <% if user_signed_in? %>
		<li<% if current_page?(visits_path); %> class="active"<% end; %>>
		  <%= link_to "Журнал посетителей", visits_path %>
		</li>
                <% end; end %>
	  </ul>
	  <ul class="nav pull-right">
		<% if admin_signed_in? %>
		<li class="dropdown">
		  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		    <%= current_admin.email %>
		    <b class="caret"></b>
		  </a>
		  <ul class="dropdown-menu">
		    <li>
		      <%= link_to 'Выйти', destroy_admin_session_path, :method => :delete %>
		    </li>
		  </ul>
		</li>
		<% end %>
		<% if user_signed_in? %>
		<li>
		<li class="dropdown">
		  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
		    <%= current_user.email %>
		    <b class="caret"></b>
		  </a>
		  <ul class="dropdown-menu">
		    <li>
		      <%= link_to 'Аккаунт', edit_user_registration_path %>
		    </li>
		    <li>
		      <%= link_to 'Выйти', destroy_user_session_path, :method => :delete %>
		    </li>
		  </ul>
		</li>
		</li>
		<% end %>
	  </ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "КПП" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>